dataset:
  image:
    name: blackhole_image
    root: dataset/blackhole_image_50k
    resolution: 256           # resolution of the images
    original_resolution: 400
    random_flip: true
    zoom_in_out: true
    zoom_range: [0.75, 1.25]
    length: 50000
  
  video:
    name: blackhole_video
    root: dataset/blackhole_video
    resolution: 256         # resolution of the images
    original_resolution: 400
    frames: 64              # number of frames in each video
    random_flip: true
    zoom_in_out: true
    zoom_range: [0.75, 1.25]
    permute: false          # [B, T ,C, H, W] -> [B, C, T, H, W]
    total_frames: 1000
    length: 1000

vae:
  model:
    in_channels: 1
    out_channels: 1
    latent_channels: 1
    down_block_types: [DownEncoderBlock2D, DownEncoderBlock2D, DownEncoderBlock2D, DownEncoderBlock2D]
    up_block_types: [UpDecoderBlock2D, UpDecoderBlock2D, UpDecoderBlock2D, UpDecoderBlock2D]
    block_out_channels: [64, 128, 256, 256]
    norm_num_groups: 16
    
  training:
    batch_size: 64
    num_workers: 8
    ema_decay: 0.99
    lr: 0.0002
    num_epochs: 25
    beta: 1e-6
    log_interval: 5
    save_interval: 25

diffusion:
  model:
    in_channels: 1
    out_channels: 1
    down_block_types: [DownBlockSpatioTemporal, DownBlockSpatioTemporal, DownBlockSpatioTemporal, DownBlockSpatioTemporal]
    up_block_types: [UpBlockSpatioTemporal, UpBlockSpatioTemporal, UpBlockSpatioTemporal, UpBlockSpatioTemporal]
    block_out_channels: [128, 256, 512, 512]
    num_attention_heads: [4, 8, 16, 16]
    layers_per_block: 2

  scheduler:
    num_train_timesteps: 1000
    beta_end: 0.02
    beta_start: 0.0001
    beta_schedule: linear
    clip_sample: false

  pre_training:
    batch_size: 4
    num_workers: 16
    ema_decay: 0.999
    lr: 0.0002
    num_epochs: 200
    log_interval: 5
    save_interval: 50

  joint_training:
    batch_size: 4
    num_workers: 16
    ema_decay: 0.999
    lr: 0.0002
    num_epochs: 500
    log_interval: 5
    save_interval: 10
    joint_ratio: 0.2
  
  # deprecated
  finetuning:
    batch_size: 4
    num_workers: 16
    ema_decay: 0.999
    lr: 0.0002
    num_epochs: 300
    log_interval: 5
    save_interval: 50
  
wandb:
  is_wandb: false
  project: STeP
  name: blackhole

target_dir: exps/blackhole_prior