dataset:
  image:
    name: mri_image
    root: dataset/mri
    resolution: 192           # resolution of the images
    random_flip: true
    clip: null
    scaling: 1e6
    image_type: real+imag
    length: 100000
  
  video:
    name: mri_video
    root: dataset/mri
    resolution: 192           # resolution of the images
    frames: 12
    random_flip: true
    clip: null
    scaling: 1e6
    image_type: real+imag
    length: 5000

vae:
  model:
    in_channels: 2
    out_channels: 2
    latent_channels: 2
    down_block_types: [DownEncoderBlock2D, DownEncoderBlock2D, DownEncoderBlock2D]
    up_block_types: [UpDecoderBlock2D, UpDecoderBlock2D, UpDecoderBlock2D]
    block_out_channels: [256, 512, 512]
    norm_num_groups: 32
    
  training:
    batch_size: 16
    num_workers: 8
    ema_decay: 0.99
    lr: 0.0002
    num_epochs: 200
    beta: 1e-6 #1e-8
    log_interval: 1
    save_interval: 5

diffusion:
  model:
    in_channels: 2
    out_channels: 2
    down_block_types: [DownBlockSpatioTemporal, DownBlockSpatioTemporal, DownBlockSpatioTemporal, DownBlockSpatioTemporal]
    up_block_types: [UpBlockSpatioTemporal, UpBlockSpatioTemporal, UpBlockSpatioTemporal, UpBlockSpatioTemporal]
    block_out_channels: [128, 256, 512, 512]
    num_attention_heads: [4, 8, 16, 16]
    layers_per_block: 2

  scheduler:
    num_train_timesteps: 1000
    beta_end: 0.02
    beta_start: 0.0001
    beta_schedule: linear
    clip_sample: false

  pre_training:
    batch_size: 16
    num_workers: 2
    ema_decay: 0.999
    lr: 0.0002
    num_epochs: 200
    log_interval: 1
    save_interval: 50

  joint_training:
    batch_size: 16
    num_workers: 2
    ema_decay: 0.999
    lr: 0.0002
    num_epochs: 500
    log_interval: 2
    save_interval: 10
    joint_ratio: 0.2
  
  # deprecated
  finetuning:
    batch_size: 4
    num_workers: 16
    ema_decay: 0.999
    lr: 0.0002
    num_epochs: 300
    log_interval: 5
    save_interval: 50

p_diffusion:
  model:
    in_channels: 2
    out_channels: 2
    down_block_types: [DownBlockSpatioTemporal, DownBlockSpatioTemporal, DownBlockSpatioTemporal, DownBlockSpatioTemporal]
    up_block_types: [UpBlockSpatioTemporal, UpBlockSpatioTemporal, UpBlockSpatioTemporal, UpBlockSpatioTemporal]
    block_out_channels: [128, 256, 512, 512]
    num_attention_heads: [4, 8, 16, 16]
    layers_per_block: 2

  scheduler:
    num_train_timesteps: 1000
    beta_end: 0.02
    beta_start: 0.0001
    beta_schedule: linear
    clip_sample: false

  training:
    batch_size: 1
    num_workers: 0
    ema_decay: 0.999
    lr: 0.0002
    num_epochs: 500
    log_interval: 1
    save_interval: 10
    joint_ratio: 0.2
  

wandb:
  is_wandb: false
  project: STeP
  name: mri

target_dir: exps/mri_prior