test_idx: [3, 12, 20, 36, 38, 39, 46, 53, 54, 55, 57, 58, 62, 67, 71, 72, 75, 77, 96, 99]


diffusion_wrapper:
  name: st_diffusion
  vdm_or_path: # [IMPORTANT] modify the path to the vdm model
  vae_or_path: # [IMPORTANT] modify the path to the vae model
  scheduler_or_path: # [IMPORTANT] modify the path to the scheduler model
  video_shape: [64, 1, 256, 256]
  latent_shape: [64, 1, 32, 32]

forward_operator:
  name: blackhole
  array: configs/task/EHT2017.txt
  imsize: 256
  w_vis: 0
  w_amp: 0
  w_cphase: 1
  w_logcamp: 1
  w_flux: 0.26
  loss_normalize: True
  num_frames: 64
  ref_multiplier: 0.001

dataset:
  name: blackhole_video
  root: dataset/blackhole_video
  resolution: 256         # resolution of the images
  original_resolution: 400
  frames: 64              # number of frames in each video
  random_flip: false
  zoom_in_out: false
  zoom_range: [0.75, 1.25]
  permute: false          # [B, T ,C, H, W] -> [B, C, T, H, W]
  total_frames: 1000
  length: 1000

sampler:
  name: 'latent_daps'
  annealing_scheduler_config:
    name: 'edm'
    num_steps: 25
    sigma_max: 100
    sigma_min: 1e-2
    timestep: 'poly-7'

  diffusion_scheduler_config:
    name: 'edm'
    num_steps: 20
    sigma_min: 1e-5
    timestep: 'poly-7'

  mcmc_sampler_config:
    prior_solver: 'exact'
    mc_algo: 'hmc'
    num_steps: 60
    lr: 1.2e-5
    tau: 0.021
    lr_min_ratio: 0.015
    momentum: 0.0

  batch_consistency: False

evaluator: 
  name: blackhole

target_dir: exps/blackhole_imaging