test_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


diffusion_wrapper:
  name: st_diffusion
  # [IMPORTANT] modify the path to the diffusion model. Set to "null" to use our pre-trained model at https://huggingface.co/bingliangzhang00/STeP-mri
  vdm_or_path: null
  vae_or_path: null 
  scheduler_or_path: null
  # ++++++++++++++++++++
  video_shape: [12, 2, 192, 192]
  latent_shape: [12, 2, 48, 48]

dataset:
  name: mri_video
  root: dataset/mri_test
  resolution: 192           # resolution of the images
  frames: 12
  random_flip: false
  clip: null
  scaling: 1e6
  image_type: real+imag
  length: 5000

forward_operator:
  name: mri
  acc_factor: 6 # 8
  mode: same_mask
  resolution: 192
  frames: 12
  num_acs_lines: 24 # 12

sampler:
  name: 'latent_daps'
  annealing_scheduler_config:
    name: 'edm'
    num_steps: 20
    sigma_max: 100
    sigma_min: 1e-2
    timestep: 'poly-7'

  diffusion_scheduler_config:
    name: 'edm'
    num_steps: 20
    sigma_min: 1e-5
    timestep: 'poly-7'

  mcmc_sampler_config:
    prior_solver: 'exact'
    mc_algo: 'hmc'
    num_steps: 53
    lr: 1.2e-3 
    tau: 0.10
    lr_min_ratio: 0.011
    momentum: 0.83

  batch_consistency: False

evaluator: 
  name: mri

target_dir: exps/dynamic_mri